"""Represents rocket powerup"""
import pygame
COLOR = (255, 0, 0)


class Rocket:
    """Represents rocket powerup"""
    def __init__(self, x, y, target_enemy):
        """Initialize rocket powerup"""
        self.x = x
        self.y = y
        self.target_enemy = target_enemy
        self.speed = 20
        self.width = 10
        self.height = 25
        self.rect = pygame.Rect(self.x, self.y, self.width, self.height)

    def update(self):
        """Move rocket to enemy target. Code was generated by Google's Gemini AI"""
        if self.target_enemy is not None:
            dx = self.target_enemy.rect.centerx - self.rect.centerx
            dy = self.target_enemy.rect.centery - self.rect.centery

            magnitude = (dx ** 2 + dy ** 2) ** 0.5
            if magnitude != 0:
                dx /= magnitude
                dy /= magnitude

            self.x += dx * self.speed
            self.y += dy * self.speed

            self.rect.x = self.x
            self.rect.y = self.y
        else:
            self.rect.x += self.speed

    def draw(self, screen):
        """Draw rocket powerup"""
        pygame.draw.rect(screen, COLOR, self.rect)
